"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { MarketplaceCard } from "@/components/MarketplaceCard";
import { MARKETPLACE_CATEGORIES, MARKETPLACE_CONDITIONS, availableQuantity, type MarketplaceListing } from "@/lib/marketplace";

export function MarketplaceDirectory({listings,followedClubIds,savedListingIds=[],signedIn=false,initialSort="newest"}:{listings:MarketplaceListing[];followedClubIds:string[];savedListingIds?:string[];signedIn?:boolean;initialSort?:string}){
 const router=useRouter();const [query,setQuery]=useState(""); const [category,setCategory]=useState("all"); const [condition,setCondition]=useState("all"); const [location,setLocation]=useState(""); const [minPrice,setMinPrice]=useState(""); const [maxPrice,setMaxPrice]=useState(""); const [available,setAvailable]=useState(false); const [followed,setFollowed]=useState(false); const [sort,setSort]=useState(initialSort);
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase(); const filtered=listings.filter(item=>(!needle||`${item.title} ${item.description}`.toLowerCase().includes(needle))&&(category==="all"||item.category===category)&&(condition==="all"||item.condition===condition)&&(!location.trim()||item.location.toLowerCase().includes(location.trim().toLowerCase()))&&(!minPrice||Number(item.price)>=Number(minPrice))&&(!maxPrice||Number(item.price)<=Number(maxPrice))&&(!available||availableQuantity(item)>0)&&(!followed||!!item.club_id&&followedClubIds.includes(item.club_id)));return [...filtered].sort((a,b)=>{const newest=new Date(b.created_at).getTime()-new Date(a.created_at).getTime();if(sort==="price_low")return Number(a.price)-Number(b.price)||newest;if(sort==="price_high")return Number(b.price)-Number(a.price)||newest;if(sort==="most_sold")return b.quantity_sold-a.quantity_sold||newest;return newest});},[listings,query,category,condition,location,minPrice,maxPrice,available,followed,followedClubIds,sort]);
 return <><section className="mt-6 rounded-[14px] border border-[#1e3a5f] bg-[#0d1f38] p-4"><label className="sr-only" htmlFor="market-search">Search Marketplace</label><input id="market-search" value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Search cues, chalk, cases…" className="min-h-12 w-full rounded-[10px] border border-[#1e3a5f] bg-[#0a1628] px-4 text-sm text-white outline-none placeholder:text-[#6b8bab] focus:border-[#4dd8c4]"/>
 <div className="mt-3 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setCategory("all")} className={`market-pill ${category==="all"?"market-pill-active":""}`}>All</button>{MARKETPLACE_CATEGORIES.map(([id,label])=><button key={id} onClick={()=>setCategory(id)} className={`market-pill whitespace-nowrap ${category===id?"market-pill-active":""}`}>{label}</button>)}</div>
 <details className="mt-3"><summary className="cursor-pointer text-xs font-black text-[#9db4d1]">More filters</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><select value={condition} onChange={e=>setCondition(e.target.value)} className="market-input"><option value="all">Any condition</option>{MARKETPLACE_CONDITIONS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><input className="market-input" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location"/><input className="market-input" type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="Min price"/><input className="market-input" type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Max price"/></div></details>
 <div className="mt-3 flex flex-wrap items-center gap-2"><button aria-pressed={available} onClick={()=>setAvailable(v=>!v)} className={`market-pill ${available?"market-pill-active":""}`}>Available only</button><button aria-pressed={followed} onClick={()=>setFollowed(v=>!v)} className={`market-pill ${followed?"market-pill-active":""}`}>Clubs you follow</button><label className="ml-auto text-xs font-bold text-[#9db4d1]">Sort <select value={sort} onChange={e=>{const next=e.target.value;setSort(next);router.replace(next==="newest"?"/marketplace":`/marketplace?sort=${next}`,{scroll:false})}} className="market-input ml-2"><option value="newest">Newest first</option><option value="price_low">Price: low to high</option><option value="price_high">Price: high to low</option><option value="most_sold">Most sold</option></select></label></div></section>
 {visible.length?<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(item=><MarketplaceCard key={item.id} listing={item} saved={savedListingIds.includes(item.id)} signedIn={signedIn}/>)}</div>:<div className="mt-5 rounded-[14px] border border-dashed border-[#1e3a5f] bg-[#0d1f38] p-10 text-center"><h2 className="font-semibold text-white">No listings match those filters.</h2><p className="mt-2 text-sm text-[#9db4d1]">Try a wider search—or be the first to sell that gear here.</p></div>}</>;
}
