"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createMarketplaceListing } from "@/lib/cloud/marketplace";
import { MARKETPLACE_CATEGORIES, MARKETPLACE_CONDITIONS, type MarketplaceCategory, type MarketplaceCondition } from "@/lib/marketplace";

export function MarketplaceListingForm({clubs}:{clubs:{id:string;name:string}[]}){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [photos,setPhotos]=useState<File[]>([]);
 async function submit(form:FormData){setBusy(true);setMessage("");try{const id=await createMarketplaceListing({title:String(form.get("title")),description:String(form.get("description")),category:String(form.get("category")) as MarketplaceCategory,condition:String(form.get("condition")) as MarketplaceCondition,price:Number(form.get("price")),currency:String(form.get("currency")),quantityTotal:Number(form.get("quantity")),location:String(form.get("location")),clubId:String(form.get("club_id")||"")||null},photos);router.push(`/marketplace/${id}`);}catch(error){setMessage(error instanceof Error?error.message:"The listing could not be published.");setBusy(false);}}
 return <form action={submit} className="mx-auto max-w-2xl space-y-5 rounded-[14px] border border-[#1e3a5f] bg-[#0d1f38] p-5 sm:p-7"><div><label className="market-label" htmlFor="photos">Photos (up to 5)</label><input id="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setPhotos(Array.from(e.target.files??[]).slice(0,5))} className="market-input w-full file:mr-3 file:rounded-lg file:border-0 file:bg-[#1d9e75] file:px-3 file:py-2 file:font-black file:text-[#04342c]"/><p className="mt-1 text-[11px] text-[#6b8bab]">{photos.length} selected · JPG, PNG or WebP · 5 MB each</p></div><Field name="title" label="Title" placeholder="e.g. Predator P3 cue" minLength={3} maxLength={100}/><div className="grid gap-4 sm:grid-cols-2"><Select name="category" label="Category" options={MARKETPLACE_CATEGORIES}/><Select name="condition" label="Condition" options={MARKETPLACE_CONDITIONS}/></div><div className="grid grid-cols-[1fr_7rem] gap-4"><Field name="price" label="Price" type="number" min="0" step="0.01"/><Select name="currency" label="Currency" options={[["KES","KES"],["USD","USD"],["EUR","EUR"],["GBP","GBP"]]}/></div><Field name="quantity" label="Quantity available" type="number" min="1" max="9999" defaultValue="1"/><Field name="location" label="General location only" placeholder="e.g. Westlands, Nairobi" minLength={2} maxLength={100}/><div><label className="market-label" htmlFor="description">Description</label><textarea id="description" name="description" required minLength={10} maxLength={1500} rows={6} placeholder="Brand, size, condition details…" className="market-input w-full resize-y"/></div>{clubs.length?<Select name="club_id" label="Optional club/shop tag" options={[["","No club tag"],...clubs.map(c=>[c.id,c.name] as [string,string])]}/>:null}<p className="rounded-xl border border-[#1e3a5f] bg-[#0a1628] p-3 text-xs leading-5 text-[#9db4d1]">CueBracket does not process payment, shipping or refunds. Keep personal addresses out of the listing; agree payment and pickup privately in the listing chat.</p>{message?<p role="alert" className="text-sm font-bold text-[#F09595]">{message}</p>:null}<button disabled={busy} className="min-h-12 w-full rounded-[10px] bg-[#1d9e75] px-5 font-black text-[#04342c] disabled:opacity-50">{busy?"Publishing…":"Publish listing"}</button></form>;
}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <div><label className="market-label" htmlFor={rest.name}>{label}</label><input id={rest.name} required className="market-input w-full" {...rest}/></div>}
function Select({name,label,options}:{name:string;label:string;options:readonly(readonly[string,string])[]}){return <div><label className="market-label" htmlFor={name}>{label}</label><select id={name} name={name} className="market-input w-full">{options.map(([id,text])=><option key={id||"empty"} value={id}>{text}</option>)}</select></div>}

