import Link from "next/link";
import { AppHeader } from "@/components/AppHeader";
import { MarketplaceDirectory } from "@/components/MarketplaceDirectory";
import { DataLoadNotice } from "@/components/DataLoadNotice";
import { createClient } from "@/lib/supabase/server";
import type { MarketplaceListing } from "@/lib/marketplace";
export const metadata={title:"Pool Marketplace · CueBracket",description:"Buy and sell pool cues, cases, tables and gear locally.",alternates:{canonical:"/marketplace"}};
const validSorts=new Set(["newest","price_low","price_high","most_sold"]);
export default async function MarketplacePage({searchParams}:{searchParams:Promise<{sort?:string}>}){const requested=(await searchParams).sort??"newest";const sort=validSorts.has(requested)?requested:"newest";const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();let query=supabase.from("marketplace_listings").select("*,club:clubs(name,slug,is_verified),seller:profiles!marketplace_listings_seller_profile_fkey(display_name,username,avatar_url,seller_avg_rating,seller_review_count)").in("status",["active","sold_out"]);if(sort==="most_sold")query=query.order("quantity_sold",{ascending:false}).order("created_at",{ascending:false});else if(sort==="price_low")query=query.order("price",{ascending:true}).order("created_at",{ascending:false});else if(sort==="price_high")query=query.order("price",{ascending:false}).order("created_at",{ascending:false});else query=query.order("created_at",{ascending:false});const [{data,error},{data:follows},{data:saved}]=await Promise.all([query,user?supabase.from("club_followers").select("club_id").eq("user_id",user.id):Promise.resolve({data:[]}),user?supabase.from("marketplace_saved_listings").select("listing_id").eq("user_id",user.id):Promise.resolve({data:[]})]);return <main className="min-h-dvh bg-[#0a1628] text-white"><AppHeader/><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><header className="flex flex-col gap-5 rounded-[14px] border border-[#1e3a5f] bg-[#0d1f38] p-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#4dd8c4]">CueBracket Marketplace</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Pool gear, traded locally.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#9db4d1]">Discover cues, cases, tables and accessories. Message the seller, then arrange payment and pickup yourselves.</p></div><div className="flex gap-2"><Link href="/marketplace/saved" className="rounded-[10px] border border-[#2a4a6f] px-4 py-3 text-sm font-black text-[#9db4d1]">Saved</Link><Link href="/marketplace/mine" className="rounded-[10px] border border-[#2a4a6f] px-4 py-3 text-sm font-black text-[#9db4d1]">My listings</Link><Link href="/marketplace/new" className="rounded-[10px] bg-[#1d9e75] px-4 py-3 text-sm font-black text-[#04342c]">+ List an item</Link></div></header>{error?<div className="mt-6"><DataLoadNotice title="Marketplace is temporarily unavailable" detail="We could not safely load the latest listings. Please retry shortly."/></div>:<MarketplaceDirectory listings={(data??[]) as MarketplaceListing[]} followedClubIds={(follows??[]).map(x=>x.club_id)} savedListingIds={(saved??[]).map(x=>x.listing_id)} signedIn={!!user} initialSort={sort}/>}</div></main>}
